fragment FragmentFeaturedImage on MediaItem {
    altText
    link
    mediaItemId
    mediaItemUrl
    description
    guid
    id
    sizes
    slug
    sourceUrl
    srcSet
    mediaDetails {
        height
        width
        sizes {
            file
            fileSize
            height
            mimeType
            name
            sourceUrl
            width
        }
    }
}