fragment FragmentJournalIssueDetails on JournalIssueDetails {
  fieldGroupName
  publicationDate
  articlesInJournal(first: 20) {
    nodes {
      __typename
      slug
      ... on Article {
        articleDetails {
          displayDate
          displayOnFrontPage
          fieldGroupName
          publicationDate
          source
          subtitle
          suppressDate
          tableOfContentsTitle
        }
        id
        title
        uri
      }
    }
  }
}
