fragment FragmentFeaturedImage on MediaItem {
  altText
  link
  caption
  mediaItemId
  mediaItemUrl
  description
  guid
  id
  sizes
  slug
  sourceUrl
  srcSet
  thumbhash
  mediaDetails {
    height
    width
    sizes {
      file
      fileSize
      height
      mimeType
      name
      sourceUrl
      width
    }
  }
}
