fragment FragmentPdfItem on PdfItem {
  contentTypeName
  databaseId
  date
  dateGmt
  guid
  id
  modified
  modifiedGmt
  pdfItemId
  slug
  status
  title
  uri
  pdfItemDetails {
    fieldGroupName
    pdfFile {
      cursor
      node {
        __typename
        fileSize(size: null)
        link
        slug
        contentTypeName
        mediaItemId
        mediaItemUrl
        mediaType
        mimeType
        uri
        title
      }
    }
    relatedArticle {
      nodes {
        __typename
        ... on Article {
          articleId
          contentTypeName
          databaseId
          date
          dateGmt
          guid
          id
          modified
          modifiedGmt
          slug
          status
          title
          uri
        }
      }
    }
  }
}
