// src/graphql/queries/getArticleByUri.ts
import { gql } from 'graphql-request';
import { DetailedArticle } from '../../types/Article';

export const GET_ARTICLE_BY_URI = gql`
  query GetArticleByUri($uri: ID!) {
    article(id: $uri, idType: URI) {
      articleId
        content
        contentTypeName
        databaseId
        date
        dateGmt
        featuredImageDatabaseId
        featuredImageId
        id
        isTermNode
        modified
        modifiedGmt
        parentDatabaseId
        parentId
        password
        previewRevisionDatabaseId
        previewRevisionId
        slug
        status
        title
        uri
        articleDetails {
            displayDate
            displayOnFrontPage
            fieldGroupName
            publicationDate
            source
            subtitle
            suppressDate
            tableOfContentsTitle
            relatedPdf {
                nodes {
                    ... on PdfItem {
                        contentTypeName
                        databaseId
                        date
                        dateGmt
                        desiredSlug
                        enclosure
                        guid
                        hasPassword
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isPreview
                        isRestricted
                        isTermNode
                        link
                        modified
                        modifiedGmt
                        password
                        pdfItemId
                        previewRevisionDatabaseId
                        previewRevisionId
                        slug
                        status
                        title
                        uri
                        pdfItemDetails {
                            fieldGroupName
                            pdfFile {
                                cursor
                                node {
                                    fileSize(size: null)
                                    link
                                    mediaDetails {
                                        file
                                        height
                                        width
                                        sizes {
                                            file
                                            fileSize
                                            height
                                            mimeType
                                            name
                                            sourceUrl
                                            width
                                        }
                                    }
                                    slug
                                    sourceUrl
                                    srcSet
                                    contentTypeName
                                    contentType {
                                        node {
                                            canExport
                                            deleteWithUser
                                            description
                                            excludeFromSearch
                                            graphqlPluralName
                                            graphqlSingleName
                                            hasArchive
                                            hierarchical
                                            id
                                            isComment
                                            isContentNode
                                            isFrontPage
                                            isPostsPage
                                            isRestricted
                                            isTermNode
                                            label
                                            menuIcon
                                            menuPosition
                                            name
                                            public
                                            publiclyQueryable
                                            restBase
                                            restControllerClass
                                            showInAdminBar
                                            showInGraphql
                                            showInMenu
                                            showInNavMenus
                                            showInRest
                                            showUi
                                            uri
                                        }
                                    }
                                    mediaItemId
                                    mediaItemUrl
                                    mediaType
                                    mimeType
                                    sizes
                                    uri
                                    title
                                }
                            }
                            relatedArticle {
                                nodes {
                                    uri
                                    ... on Article {
                                        articleId
                                        content
                                        contentTypeName
                                        databaseId
                                        date
                                        dateGmt
                                        desiredSlug
                                        enclosure
                                        featuredImageDatabaseId
                                        featuredImageId
                                        guid
                                        hasPassword
                                        id
                                        isComment
                                        isContentNode
                                        isFrontPage
                                        isPostsPage
                                        isPreview
                                        isRestricted
                                        isTermNode
                                        link
                                        modified
                                        modifiedGmt
                                        parentDatabaseId
                                        parentId
                                        password
                                        previewRevisionDatabaseId
                                        previewRevisionId
                                        slug
                                        status
                                        title
                                        uri
                                    }
                                    slug
                                }
                            }
                        }
                    }
                    ... on JournalIssue {
                        contentTypeName
                        databaseId
                        date
                        dateGmt
                        desiredSlug
                        enclosure
                        featuredImageDatabaseId
                        featuredImageId
                        guid
                        hasPassword
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isPreview
                        isRestricted
                        isTermNode
                        journalIssueId
                        link
                        modified
                        modifiedGmt
                        parentDatabaseId
                        parentId
                        password
                        previewRevisionDatabaseId
                        previewRevisionId
                        slug
                        status
                        title
                        uri
                    }
                    ... on AudioItem {
                        audioItemId
                        contentTypeName
                        databaseId
                        date
                        dateGmt
                        desiredSlug
                        enclosure
                        guid
                        hasPassword
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isPreview
                        isRestricted
                        isTermNode
                        link
                        modified
                        modifiedGmt
                        parentDatabaseId
                        parentId
                        password
                        previewRevisionDatabaseId
                        previewRevisionId
                        slug
                        status
                        title
                        uri
                    }
                    ... on MediaItem {
                        altText
                        authorDatabaseId
                        authorId
                        caption
                        commentCount
                        commentStatus
                        contentTypeName
                        databaseId
                        date
                        dateGmt
                        description
                        desiredSlug
                        enclosure
                        fileSize
                        guid
                        hasPassword
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isPreview
                        isRestricted
                        isTermNode
                        link
                        mediaItemId
                        mediaItemUrl
                        mediaType
                        mimeType
                        modified
                        modifiedGmt
                        parentDatabaseId
                        parentId
                        password
                        previewRevisionDatabaseId
                        previewRevisionId
                        sizes
                        slug
                        sourceUrl
                        srcSet
                        status
                        title
                        uri
                    }
                    ... on Book {
                        authorDatabaseId
                        authorId
                        bookId
                        contentTypeName
                        databaseId
                        date
                        dateGmt
                        desiredSlug
                        enclosure
                        featuredImageDatabaseId
                        featuredImageId
                        guid
                        hasPassword
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isPreview
                        isRestricted
                        isTermNode
                        link
                        modified
                        modifiedGmt
                        parentDatabaseId
                        parentId
                        password
                        previewRevisionDatabaseId
                        previewRevisionId
                        slug
                        status
                        title
                        uri
                    }
                    ... on Article {
                        articleId
                        content
                        contentTypeName
                        databaseId
                        date
                        dateGmt
                        desiredSlug
                        enclosure
                        featuredImageDatabaseId
                        featuredImageId
                        guid
                        hasPassword
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isPreview
                        isRestricted
                        isTermNode
                        link
                        modified
                        modifiedGmt
                        parentDatabaseId
                        parentId
                        password
                        previewRevisionDatabaseId
                        previewRevisionId
                        slug
                        status
                        title
                        uri
                    }
                }
            }
        }
        featuredImage {
            cursor
            node {
                altText
                authorDatabaseId
                authorId
                caption
                contentTypeName
                databaseId
                date
                dateGmt
                description
                desiredSlug
                fileSize
                guid
                hasPassword
                id
                mediaItemId
                mediaItemUrl
                mediaType
                mimeType
                modified
                modifiedGmt
                parentDatabaseId
                parentId
                sizes
                slug
                sourceUrl
                srcSet
                title
                uri
            }
        }
    }
}
`;

export interface GetArticleByUriResponse {
  article: DetailedArticle;
}
