  query GetArticleById($id: ID!) {
    article(id: $id, idType: DATABASE_ID) {
      articleId
      content
      contentTypeName
      databaseId
      date
      dateGmt
      featuredImageDatabaseId
      featuredImageId
      id
      isTermNode
      modified
      modifiedGmt
      parentDatabaseId
      parentId
      password
      previewRevisionDatabaseId
      previewRevisionId
      slug
      status
      title
      uri
      articleDetails {
        displayDate
        displayOnFrontPage
        fieldGroupName
        publicationDate
        source
        subtitle
        suppressDate
        tableOfContentsTitle
      }
      featuredImage {
        cursor
        node {
          altText
          authorDatabaseId
          authorId
          contentTypeName
          databaseId
          dateGmt
          description
          desiredSlug
          fileSize
          guid
          hasPassword
          id
          mediaItemId
          mediaItemUrl
          mediaType
          mimeType
          modified
          modifiedGmt
          parentDatabaseId
          parentId
          sizes
          slug
          sourceUrl
          srcSet
          title
          uri
        }
      }
    }
  }
