query GetArticlesByTermDatabaseID ($uri: ID!)  {
    termNode(id: $uri, idType: DATABASE_ID) {
        count
        databaseId
        description
        id
        isTermNode
        name
        slug
        taxonomyName
        termGroupId
        termTaxonomyId
        uri
        ... on Place {
            name
            slug
            uri
            contentNodes {
                nodes {
                    ... on Article {
                        articleId
                        contentTypeName
                        databaseId
                        date
                        dateGmt
                        featuredImageDatabaseId
                        featuredImageId
                        id
                        isContentNode
                        modified
                        modifiedGmt
                        parentDatabaseId
                        parentId
                        password
                        previewRevisionDatabaseId
                        previewRevisionId
                        slug
                        status
                        title
                        uri
                        articleDetails {
                            displayDate
                            displayOnFrontPage
                            publicationDate
                            source
                            subtitle
                            suppressDate
                            tableOfContentsTitle
                        }
                    }
                }
            }
        }
        ... on Topic {
            name
            slug
            uri
            contentNodes {
                nodes {
                    ... on Article {
                        articleId
                        contentTypeName
                        databaseId
                        date
                        dateGmt
                        featuredImageDatabaseId
                        featuredImageId
                        id
                        isContentNode
                        modified
                        modifiedGmt
                        parentDatabaseId
                        parentId
                        password
                        previewRevisionDatabaseId
                        previewRevisionId
                        slug
                        status
                        title
                        uri
                        articleDetails {
                            displayDate
                            displayOnFrontPage
                            publicationDate
                            source
                            subtitle
                            suppressDate
                            tableOfContentsTitle
                        }
                    }
                }
            }
        }
    }
}
