query GetGlobalSettings {
    globalSettings {
        fGGlobalSettings {
            bannerImage {
                cursor
                node {
                    ...FragmentFeaturedImage
                }
            }
            notificationBar {
                fieldGroupName
                notificationMessage
                notificationOnoff
            }
            bannerImageTwitter {
                cursor
                node {
                    altText
                    srcSet
                    sourceUrl
                    mediaDetails {
                        height
                        width
                    }
                }
            }
            bannerImageTwitterSquare {
                cursor
                node {
                    altText
                    srcSet
                    sourceUrl
                    mediaDetails {
                        height
                        width
                    }
                }
            }
        }
    }
}
