query GetGlobalSettings {
    globalSettings {
        fGGlobalSettings {
            bannerImage {
                cursor
                node {
                    altText
                    srcSet
                    sourceUrl
                }
            }
            notificationBar {
                fieldGroupName
                notificationMessage
                notificationOnoff
            }
        }
    }
}