query GetJournalByUri($uri: String!) {
  journalIssueBy(uri: $uri) {
    title
    featuredImage {
      node {
        ...FragmentFeaturedImage
      }
    }
    journalIssueDetails {
      ...FragmentJournalIssueDetails
    }
  }
}
