query GetJournalIssues($language: LanguageCodeFilterEnum!) {
  journalIssues(where: { language: $language }) {
    nodes {
      journalIssueDetails {
        ...FragmentJournalIssueDetails
      }
      slug
      title
      featuredImage {
        node {
          ...FragmentFeaturedImage
        }
      }
      language {
        code
        locale
        name
        slug
      }
    }
  }
}