query GetJournalIssues($language: LanguageCodeFilterEnum!) {
  journalIssues(where: { language: $language }) {
    nodes {
      journalIssueDetails {
        articlesInJournal {
          nodes {
            ... on Article {
              articleDetails {
                displayDate
                displayOnFrontPage
                fieldGroupName
                publicationDate
                source
                subtitle
                suppressDate
                tableOfContentsTitle
              }
              title
              __typename
              slug
              id
            }
            slug
          }
        }
        fieldGroupName
        publicationDate
      }
      slug
      title
      featuredImage {
        node {
          ...FragmentFeaturedImage
        }
      }
      language {
        code
        locale
        name
        slug
      }
    }
  }
}
